/**
 * Phonogram English Poetic Unit Tests
 * ====================================
 */
import {poetic} from '../../src/english';

export default {
  fn: poetic,
  cases: [
    ['actions', 'akʃʌnz'],
    ['administrative', 'administrativ'],
    ['age', 'ɛjdʒ'],
    ['air', 'ɛr'],
    ['and', 'ɛnd'],
    ['arson', 'arsɔn'],
    ['at', 'at'],
    ['ate', 'ɛjt'],
    ['awe', 'o'],

    ['Bateson', 'bɛjtsɔn'],
    ['bind', 'bajnd'],
    ['bit', 'bit'],
    ['bite', 'bajt'],
    ['blight', 'blajt'],
    ['blind', 'blajnd'],
    ['bomb', 'bɔmb'],
    ['bombs', 'bɔmbz'],
    ['bone', 'bon'],
    ['bones', 'bonz'],
    ['boy', 'bɔj'],
    ['Britain', 'britɛjn'],

    ['can', 'kan'],
    ['cane', 'kɛjn'],
    ['cap', 'kap'],
    ['cape', 'kɛjp'],
    ['castle', 'kasʌl'],
    ['celt', 'sɛlt'],
    ['charity', 'tʃariti'],
    ['chores', 'tʃɔrz'],
    ['cistern', 'sistʌrn'],
    ['cloakroom', 'klokrum'],
    ['cruel', 'krul'],
    ['crumb', 'krʌmb'],
    ['cue', 'kju'],
    ['cute', 'kjut'],

    ['day', 'dɛ'],
    ['debate', 'dibɛjt'],
    ['dew', 'dju'],
    ['dictionary', 'dikʃʌnɛri'],
    ['dim', 'dim'],
    ['dime', 'dajm'],
    ['do', 'du'],
    ['door', 'dɔr'],
    ['duchess', 'dʌtʃɛs'],
    ['duck', 'dʌk'],

    ['eccentric', 'iksɛntrik'],
    ['equal', 'ikwol'],
    ['end', 'ɛnd'],
    ['endgame', 'ɛndgɛjm'],
    ['energy', 'ɛnʌrdʒi'],

    ['few', 'fju'],
    ['find', 'fajnd'],
    ['five', 'fajv'],
    ['fir', 'fʌr'],
    ['fire', 'fajʌr'],
    ['flair', 'flɛr'],

    ['geography', 'dʒiografi'],
    ['George', 'dʒɔrdʒ'],
    ['Gerard', 'dʒʌrard'],
    ['gladly', 'gladli'],
    ['gloomy', 'glumi'],
    ['grace', 'grɛjs'],
    ['greek', 'grik'],
    ['grinding', 'grajnding'],

    ['Harry', 'hari'],
    ['hello', 'hɛlo'],

    ['Italy', 'itali'],

    ['Jameson', 'dʒɛjmsɔn'],
    ['Jerry', 'dʒɛri'],
    ['jews', 'dʒuz'],
    ['jib', 'dʒib'],
    ['jibe', 'dʒajb'],
    ['jive', 'dʒajv'],
    ['Jordan', 'dʒɔrdan'],
    ['junk', 'dʒʌnk'],

    ['kind', 'kajnd'],
    ['knew', 'nu'],

    ['leaders', 'lidʌrz'],
    ['lesson', 'lɛsɔn'],
    ['life', 'lajf'],
    ['lion', 'lajɔn'],
    ['lions', 'lajɔnz'],
    ['live', 'liv'],
    ['loo', 'lu'],

    ['make', 'mɛjk'],
    ['mat', 'mat'],
    ['mind', 'majnd'],
    ['minds', 'majndz'],
    ['mine', 'majn'],
    ['moat', 'mot'],
    ['Moose', 'muz'],

    ['nay', 'nɛ'],
    ['new', 'nju'],
    ['night', 'najt'],
    ['notorious', 'notɔrjʌs'],
    ['notoriously', 'notɔrjʌsli'],

    ['off', 'ɔf'],
    ['offspring', 'ɔfspring'],

    ['pet', 'pɛt'],
    ['Pete', 'pit'],
    ['Peter', 'pitʌr'],
    ['phew', 'fju'],
    ['philosophy', 'filozɔfi'],
    ['pin', 'pin'],
    ['pine', 'pajn'],
    ['pity', 'piti'],
    ['place', 'plɛjs'],
    ['plaice', 'plɛjs'],
    ['plead', 'plid'],
    ['poor', 'pur'],
    ['pot', 'pɔt'],
    ['programmable', 'programabʌl'],
    ['Putney', 'pʌtni'],

    ['Quentin', 'kwɛntin'],

    ['ration', 'raʃʌn'],
    ['receipt', 'risit'],
    ['receipts', 'risits'],
    ['receive', 'risiv'],
    ['rescind', 'risind'],
    ['retail', 'ritɛjl'],
    ['riot', 'rajɔt'],
    ['raw', 'ro'],

    ['sea', 'si'],
    ['see', 'si'],
    ['Shampoo', 'ʃampu'],
    ['shemale', 'ʃimɛjl'],
    ['size', 'sajz'],
    ['sire', 'sajʌr'],
    ['sister', 'sistʌr'],
    ['sit', 'sit'],
    ['site', 'sajt'],
    ['Stephen', 'stivʌn'],
    ['Steven', 'stivʌn'],
    ['still', 'stil'],

    ['tail', 'tɛjl'],
    ['tee', 'ti'],
    ['to', 'tu'],
    ['tomb', 'tumb'],
    ['twice', 'twajs'],
    ['two', 'tu'],

    ['Ulfric', 'ʌlfrik'],
    ['unique', 'junik'],

    ['Vaughn', 'vɔn'],
    ['Vaughan', 'vɔn'],

    ['young', 'jʌng'],

    ['wall', 'wol'],
    ['Warwick', 'worik'],
    ['what', 'wat'],
    ['who', 'hu'],
    ['whom', 'hum'],
    ['whose', 'huz'],
    ['William', 'wiljam'],
    ['wombs', 'wumbz'],
    ['wood', 'wud'],
    ['Worcester', 'wɔrstʌr'],
    ['wrestle', 'rɛsʌl'],
    ['wrestler', 'rɛslʌr'],
    ['wrestling', 'rɛsling'],
    ['wrist', 'rist']
  ]
};
