/**
 * Phonogram English Poetic Unit Tests
 * ====================================
 */
import {poetic} from '../../src/english';

export default {
  fn: poetic,
  cases: [
    ['actions', 'akʃʌnz'],
    ['administrative', 'administrativ'],
    ['age', 'ɛjdʒ'],
    ['air', 'ɛr'],
    ['ancestry', 'ansɛstri'],
    ['and', 'ɛnd'],
    ['arson', 'arsɔn'],
    ['at', 'at'],
    ['ate', 'ɛjt'],
    ['awe', 'o'],

    ['Bateson', 'bɛjtsɔn'],
    ['bind', 'bajnd'],
    ['bit', 'bit'],
    ['bite', 'bajt'],
    ['blight', 'blajt'],
    ['blind', 'blajnd'],
    ['bomb', 'bɔmb'],
    ['bombs', 'bɔmbz'],
    ['bone', 'bon'],
    ['bones', 'bonz'],
    ['boy', 'bɔj'],
    ['Britain', 'britɛjn'],

    ['can', 'kan'],
    ['cane', 'kɛjn'],
    ['cap', 'kap'],
    ['cape', 'kɛjp'],
    ['castle', 'kasʌl'],
    ['celt', 'sɛlt'],
    ['charity', 'tʃariti'],
    ['chores', 'tʃɔrz'],
    ['cistern', 'sistʌrn'],
    ['cloakroom', 'klokrum'],
    ['convey', 'kɔnvɛ'],
    ['cruel', 'krul'],
    ['crumb', 'krʌmb'],
    ['cue', 'kju'],
    ['cute', 'kjut'],

    ['day', 'dɛ'],
    ['debate', 'dibɛjt'],
    ['dew', 'dju'],
    ['dictionary', 'dikʃʌnɛri'],
    ['dim', 'dim'],
    ['dime', 'dajm'],
    ['do', 'du'],
    ['door', 'dɔr'],
    ['duchess', 'dʌtʃɛs'],
    ['duck', 'dʌk'],

    ['eccentric', 'iksɛntrik'],
    ['egg', 'ɛg'],
    ['equal', 'ikwol'],
    ['end', 'ɛnd'],
    ['endgame', 'ɛndgɛjm'],
    ['energy', 'ɛnʌrdʒi'],

    ['few', 'fju'],
    ['find', 'fajnd'],
    ['five', 'fajv'],
    ['fir', 'fʌr'],
    ['fire', 'fajʌr'],
    ['flair', 'flɛr'],
    ['flies', 'flajz'],
    ['fly', 'flaj'],
    ['flying', 'flajing'],
    ['fries', 'frajz'],
    ['fry', 'fraj'],
    ['frying', 'frajing'],
    ['forestry', 'fɔrɛstri'],

    ['geography', 'dʒiografi'],
    ['George', 'dʒɔrdʒ'],
    ['Gerard', 'dʒʌrard'],
    ['germ', 'dʒʌrm'],
    ['germs', 'dʒʌrmz'],
    ['gladly', 'gladli'],
    ['gloomy', 'glumi'],
    ['grace', 'grɛjs'],
    ['greek', 'grik'],
    ['grinding', 'grajnding'],

    ['Harry', 'hari'],
    ['hello', 'hɛlo'],
    ['house', 'haʊs'],
    ['housing', 'haʊsing'],
    ['hue', 'hju'],

    ['imbue', 'imbju'],
    ['Italy', 'itali'],

    ['Jameson', 'dʒɛjmsɔn'],
    ['Jerry', 'dʒɛri'],
    ['jews', 'dʒuz'],
    ['jib', 'dʒib'],
    ['jibe', 'dʒajb'],
    ['jive', 'dʒajv'],
    ['Jordan', 'dʒɔrdan'],
    ['junk', 'dʒʌnk'],

    ['kind', 'kajnd'],
    ['knew', 'nu'],

    ['language', 'langwɛjdʒ'],
    ['leaders', 'lidʌrz'],
    ['lesson', 'lɛsɔn'],
    ['life', 'lajf'],
    ['lion', 'lajɔn'],
    ['lions', 'lajɔnz'],
    ['live', 'liv'],
    ['loo', 'lu'],

    ['make', 'mɛjk'],
    ['mat', 'mat'],
    ['mice', 'majs'],
    ['mickey', 'miki'],
    ['mind', 'majnd'],
    ['minds', 'majndz'],
    ['mine', 'majn'],
    ['moat', 'mot'],
    ['Moose', 'muz'],
    ['mouse', 'maʊs'],
    ['my', 'maj'],

    ['nay', 'nɛ'],
    ['new', 'nju'],
    ['night', 'najt'],
    ['notorious', 'notɔrjʌs'],
    ['notoriously', 'notɔrjʌsli'],

    ['obbey', 'ɔbɛ'],
    ['off', 'ɔf'],
    ['offspring', 'ɔfspring'],

    ['pet', 'pɛt'],
    ['Pete', 'pit'],
    ['Peter', 'pitʌr'],
    ['phew', 'fju'],
    ['philosophy', 'filozɔfi'],
    ['piece', 'pis'],
    ['pieces', 'pisiz'],
    ['pin', 'pin'],
    ['pine', 'pajn'],
    ['pity', 'piti'],
    ['place', 'plɛjs'],
    ['plaice', 'plɛjs'],
    ['plead', 'plid'],
    ['poor', 'pur'],
    ['pot', 'pɔt'],
    ['programmable', 'programabʌl'],
    ['Putney', 'pʌtni'],

    ['Quentin', 'kwɛntin'],

    ['ration', 'raʃʌn'],
    ['receipt', 'risit'],
    ['receipts', 'risits'],
    ['receive', 'risiv'],
    ['rescind', 'risind'],
    ['retail', 'ritɛjl'],
    ['right', 'rajt'],
    ['riot', 'rajɔt'],
    ['raw', 'ro'],
    ['Ryan', 'rajan'],

    ['sea', 'si'],
    ['see', 'si'],
    ['Shampoo', 'ʃampu'],
    ['shemale', 'ʃimɛjl'],
    ['simplify', 'simplifaj'],
    ['sire', 'sajʌr'],
    ['sister', 'sistʌr'],
    ['sit', 'sit'],
    ['site', 'sajt'],
    ['size', 'sajz'],
    ['Stephen', 'stivʌn'],
    ['Steven', 'stivʌn'],
    ['still', 'stil'],
    ['survey', 'sʌrvɛ'],

    ['tail', 'tɛjl'],
    ['tee', 'ti'],
    ['that', 'ðat'],
    ['Thatcher', 'θatʃʌr'],
    ['thee', 'ði'],
    ['their', 'ðɛr'],
    ['theirs', 'ðɛrz'],
    ['them', 'ðɛm'],
    ['themself', 'ðɛmsɛlf'],
    ['themselves', 'ðɛmsɛlvz'],
    ['these', 'ðiz'],
    ['they', 'ðɛ'],
    ['thine', 'ðajn'],
    ['this', 'ðis'],
    ['those', 'ðoz'],
    ['thou', 'ðaʊ'],
    ['thy', 'ðaj'],
    ['thyself', 'ðajsɛlf'],
    ['Thom', 'tɔm'],
    ['Thomas', 'tɔmas'],
    ['to', 'tu'],
    ['tomb', 'tumb'],
    ['try', 'traj'],
    ['trying', 'trajing'],
    ['twice', 'twajs'],
    ['two', 'tu'],

    ['Ulfric', 'ʌlfrik'],
    ['unique', 'junik'],

    ['Vaughn', 'vɔn'],
    ['Vaughan', 'vɔn'],
    ['violence', 'vajolɛns'],

    ['young', 'jʌng'],

    ['wall', 'wol'],
    ['Warwick', 'worik'],
    ['what', 'wat'],
    ['who', 'hu'],
    ['whom', 'hum'],
    ['whose', 'huz'],
    ['William', 'wiljam'],
    ['wombs', 'wumbz'],
    ['wood', 'wud'],
    ['Worcester', 'wɔrstʌr'],
    ['wrestle', 'rɛsʌl'],
    ['wrestler', 'rɛslʌr'],
    ['wrestling', 'rɛsling'],
    ['wright', 'rajt'],
    ['wrist', 'rist']
  ]
};
