/**
 * Phonogram French Poetic Unit Tests
 * ===================================
 */
import {poetic} from '../../src/french';

export default {
  fn: poetic,
  cases: [
    ['abasourdie', 'abazurdi'],
    ['abeille', 'abɛj'],
    ['Abidjan', 'abidʒã'],
    ['aigüe', 'ɛgy'],
    ['aiguës', 'ɛgy'],
    ['ail', 'aj'],
    ['almanach', 'almana'],
    ['accentuation', 'aksãtyasjõ'],
    ['âme', 'am'],
    ['ambiance', 'ãbjãs'],
    ['amphétamine', 'ãfetamin'],
    ['an', 'ã'],
    ['antagoniste', 'ãtagonist'],
    ['antisocial', 'ãtisosjal'],
    ['aplomb', 'aplõ'],
    ['arabesque', 'arabɛsk'],
    ['arhe', 'ar'],
    ['aux', 'o'],
    ['Auxerres', 'osɛr'],
    ['auxilliaire', 'oksiljɛr'],
    ['ayant', 'ɛjã'],
    ['ayatollah', 'ajatola'],
    ['ayez', 'ɛje'],

    ['Bach', 'bak'],
    ['baignoire', 'bɛnwar'],
    ['barbecue', 'barbøkju'],
    ['beauvillaine', 'bovilɛn'],
    ['bel', 'bɛl'],
    ['belle', 'bɛl'],
    ['belles', 'bɛl'],
    ['beau', 'bo'],
    ['bibelot', 'bibelo'],
    ['bitte', 'bit'],
    ['blanc', 'blã'],
    ['bœuf', 'bøf'],
    ['bogoss', 'bogos'],
    ['bonbon', 'bõbõ'],
    ['bretzel', 'bretsɛl'],
    ['Bruxelles', 'brysɛl'],
    ['buisson', 'bɥisõ'],

    ['cacochyme', 'kakoʃim'],
    ['caecum', 'sekʌm'],
    ['cæcal', 'sekal'],
    ['calmement', 'kalmømã'],
    ['camembert', 'kamãbɛr'],
    ['cartes', 'kart'],
    ['cases', 'kaz'],
    ['cerf', 'sɛr'],
    ['chaire', 'ʃɛr'],
    ['chateau', 'ʃato'],
    ['chateaux', 'ʃato'],
    ['chemin', 'ʃømẽ'],
    ['chevreuil', 'ʃøvrøj'],
    ['chien', 'ʃjẽ'],
    ['chnoque', 'ʃnɔk'],
    ['chorizo', 'ʃorizo'],
    ['chrysanthème', 'krizãtɛm'],
    ['chtonien', 'ktonjẽ'],
    ['claymore', 'klɛmor'],
    ['clef', 'kle'],
    ['cloque', 'klɔk'],
    ['coelacanthe', 'kølakãt'],
    ['cœlacanthe', 'kølakãt'],
    ['coing', 'kwẽ'],
    ['coings', 'kwẽ'],
    ['coït', 'koit'],
    ['coit', 'kwa'],
    ['cool', 'kul'],
    ['confidentiel', 'kõfidãsjɛl'],
    ['confidentielle', 'kõfidãsjɛl'],
    ['conne', 'kɔn'],
    ['constitution', 'kõstitysjõ'],
    ['contestation', 'kõtɛstasjõ'],
    ['coucou', 'kuku'],
    ['couille', 'kuj'],
    ['cruel', 'kryɛl'],
    ['cul', 'ky'],

    ['daim', 'dẽ'],
    ['darmstadt', 'darmstat'],
    ['démocratie', 'demokrasi'],
    ['dessein', 'desẽ'],
    ['deuil', 'døj'],
    ['dévorée', 'devore'],
    ['doigt', 'dwa'],

    ['effet', 'efɛ'],
    ['emmerder', 'ãmɛrde'],
    ['empâtement', 'ãpatømã'],
    ['essaim', 'esẽ'],
    ['ès', 'ɛs'],
    ['es', 'ɛ'],
    ['est', 'ɛ'],
    ['et', 'e'],
    ['euphorie', 'øfori'],
    ['eu', 'y'],
    ['eusse', 'ys'],
    ['eussiez', 'ysje'],
    ['Eustache', 'østaʃ'],
    ['eût', 'y'],
    ['eux', 'ø'],
    ['excalibur', 'ekskalibyr'],
    ['exception', 'eksepsjõ'],
    ['excitation', 'eksitasjõ'],
    ['exulter', 'egzylte'],
    ['exutoire', 'egzytwar'],

    ['faisan', 'føzã'],
    ['faisons', 'føzõ'],
    ['faisiez', 'føzje'],
    ['faon', 'fã'],
    ['femme', 'fam'],
    ['fenouil', 'fønuj'],
    ['fête', 'fɛt'],
    ['finaux', 'fino'],
    ['floc', 'flɔk'],
    ['flop', 'flɔp'],
    ['fluet', 'flyɛ'],
    ['forestier', 'forɛstje'],
    ['forêt', 'forɛ'],
    ['fouine', 'fuin'],

    ['gageure', 'gaʒyr'],
    ['galop', 'galo'],
    ['gaufres', 'gofr'],
    ['genoux', 'ʒenu'],
    ['gérard', 'ʒerar'],
    ['gleyre', 'glɛr'],
    ['gout', 'gu'],
    ['goût', 'gu'],
    ['gnaquer', 'njake'],
    ['gnognotte', 'njonjɔt'],
    ['gnôle', 'njol'],
    ['gnon', 'njõ'],
    ['gnosticisme', 'gnostisism'],
    ['gnou', 'gnu'],
    ['guillaume', 'gijom'],

    ['hasard', 'azar'],
    ['haschich', 'aʃiʃ'],
    ['hêtre', 'ɛtr'],
    ['homosexuel', 'omoseksyɛl'],
    ['horrible', 'oribl'],
    ['hun', 'ẽ'],

    ['illégal', 'illegal'],
    ['imbu', 'ẽby'],
    ['inquiet', 'ẽkjɛ'],
    ['inquisition', 'ẽkizisjõ'],

    ['javelot', 'ʒavelo'],
    ['jeu', 'ʒø'],
    ['jeun', 'ʒẽ'],
    ['julie', 'ʒyli'],

    ['laitue', 'lɛty'],
    ['lapin', 'lapẽ'],
    ['litigieuse', 'litiʒjøz'],
    ['Livaro', 'livaro'],
    ['lunaire', 'lynɛr'],
    ['lyncher', 'lẽʃe'],

    ['manger', 'mãʒe'],
    ['manteau', 'mãto'],
    ['mes', 'mɛ'],
    ['mesclun', 'mɛsklẽ'],
    ['messieurs', 'mesjø'],
    ['mezzanine', 'mɛdzanin'],
    ['milliard', 'miljar'],
    ['milliers', 'milje'],
    ['million', 'miljõ'],
    ['monsieur', 'møsjø'],
    ['monsieurs', 'møsjø'],
    ['montez', 'mõte'],
    ['motclef', 'mokle'],
    ['motte', 'mɔt'],
    ['Munster', 'mẽstɛr'],
    ['Münster', 'mẽstɛr'],

    ['nerf', 'nɛr'],
    ['nimbée', 'nẽbe'],
    ['noir', 'nwar'],
    ['nos', 'no'],
    ['noyau', 'nwajo'],
    ['noyauter', 'nwajote'],

    ['oeil', 'øj'],
    ['œil', 'øj'],
    ['oeuf', 'øf'],
    ['oiseau', 'wazo'],
    ['ombres', 'õbr'],
    ['oreille', 'orɛj'],
    ['ornithorynque', 'ornitorẽk'],
    ['ôter', 'ote'],
    ['où', 'u'],
    ['oyez', 'oje'],

    ['pain', 'pẽ'],
    ['paon', 'pã'],
    ['parpaing', 'parpẽ'],
    ['parterre', 'partɛr'],
    ['patronage', 'patronaʒ'],
    ['pestacle', 'pɛstakl'],
    ['pharisien', 'farizjẽ'],
    ['pharynx', 'farẽks'],
    ['plomb', 'plõ'],
    ['plombes', 'plõb'],
    ['pneu', 'pnø'],
    ['poing', 'pwẽ'],
    ['point', 'pwẽ'],
    ['poix', 'pwa'],
    ['pomme', 'pɔm'],
    ['pommes', 'pɔm'],
    ['pommeaux', 'pomo'],
    ['posément', 'pozemã'],
    ['poubelle', 'pubɛl'],
    ['poux', 'pu'],
    ['proc', 'prɔk'],
    ['puissamment', 'pɥisamã'],

    ['quadrilatère', 'kwadrilatɛr'],
    ['qualité', 'kalite'],
    ['quantité', 'kãtite'],
    ['quartz', 'kwarts'],
    ['quidam', 'kidam'],
    ['quoi', 'kwa'],

    ['rach', 'rak'],
    ['rat', 'ra'],
    ['rayon', 'rɛjõ'],
    ['rayoner', 'rɛjone'],
    ['reine', 'rɛn'],
    ['remerciements', 'rømɛrsimã'],
    ['renne', 'rɛn'],
    ['requartzifier', 'røkwartsifje'],
    ['resurgir', 'røsyrʒir'],
    ['rhume', 'rym'],
    ['roi', 'rwa'],
    ['roy', 'rwa'],
    ['rote', 'rɔt'],
    ['roter', 'rote'],

    ['salop', 'salo'],
    ['salut', 'saly'],
    ['sagement', 'saʒømã'],
    ['savon', 'savõ'],
    ['sashimi', 'saʃimi'],
    ['scenario', 'senarjo'],
    ['schnock', 'ʃnɔk'],
    ['schnoque', 'ʃnɔk'],
    ['sciemment', 'sjamã'],
    ['scotcher', 'skotʃe'],
    ['sensation', 'sãsasjõ'],
    ['sensationnel', 'sãsasjonɛl'],
    ['serf', 'sɛr'],
    ['ses', 'sɛ'],
    ['shawarma', 'ʃawarma'],
    ['souhaites', 'suɛt'],
    ['squale', 'skwal'],
    ['Staël', 'stɛl'],
    ['susurrer', 'sysyre'],
    ['synthèse', 'sẽtɛz'],
    ['synthétique', 'sẽtetik'],
    ['syrop', 'siro'],

    ['tapecul', 'tapky'],
    ['terrain', 'tɛrrẽ'],
    ['tes', 'tɛ'],
    ['thérapie', 'terapi'],
    ['tiare', 'tjar'],
    ['toc', 'tɔk'],
    ['top', 'tɔp'],
    ['toque', 'tɔk'],
    ['toquer', 'toke'],
    ['toutou', 'tutu'],
    ['troène', 'troɛn'],
    ['tronc', 'trõ'],
    ['trop', 'tro'],
    ['truelle', 'tryɛl'],
    ['tunnel', 'tynɛl'],

    ['un', 'ẽ'],
    ['unitaire', 'ynitɛr'],

    ['vademecum', 'vademekʌm'],
    ['vair', 'vɛr'],
    ['verre', 'vɛr'],
    ['villa', 'villa'],
    ['villain', 'vilẽ'],
    ['vos', 'vo'],

    ['wagon', 'vagõ'],
    ['wapiti', 'wapiti'],

    ['xylophone', 'gzilofon'],

    ['yannick', 'janik'],
    ['yeux', 'jø'],

    ['zèbre', 'zɛbr'],
    ['zoo', 'zoo'],
    ['zoologie', 'zooloʒi'],
    ['zyeuter', 'zjøte']
  ]
};
